SELECT * FROM article a;
SELECT REF FROM article a
WHERE a.PRIX > 2;
SELECT * FROM article a 
WHERE a.PRIX BETWEEN 2 AND 6.25;
SELECT * FROM article a 
WHERE a.PRIX NOT BETWEEN 2 AND 6.25
AND a.ID_FOU = 1
ORDER BY a.PRIX DESC;
SELECT * FROM article a
WHERE a.ID_FOU = 1 OR a.ID_FOU = 3;
SELECT * FROM article a
WHERE a.ID_FOU IN (1, 3);
SELECT * FROM article a
WHERE a.ID_FOU NOT IN (1, 3);
SELECT * FROM bon b
WHERE b.DATE_CMDE NOT BETWEEN '2019-02-01' AND '2019-04-30';